name: Gitee
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo and time
        id: info
        uses: actions/github-script@v3.1
        with:
          result-encoding: string
          script: |
            core.setOutput('time', new Date(Date.now()).toISOString().replace(/[^0-9]/g, ""));
            core.setOutput('key', `${context.repo.owner}-${context.repo.repo}`);
            return context.repo.repo;

      - name: Cache src repos
        uses: actions/cache@v2.1.3
        id: cache
        with:
          path: ${{ github.workspace }}/hub-mirror-cache
          key: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-${{ steps.info.outputs.time }}
          restore-keys: ${{ runner.os }}-${{ steps.info.outputs.key }}-cache-
      - name: Sync To Gitee
        uses: Yikun/hub-mirror-action@v1.0
        with:
          src: github/zf1976
          dst: gitee/zf1976
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          cache_path: /github/workspace/hub-mirror-cache
          account_type: user
          debug: true
          force_update: true
          static_list: 'vdns'
